# Generated by Django 4.1.4 on 2022-12-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claritymedapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=50, verbose_name='תז רופא')),
                ('doc_name', models.CharField(max_length=50, verbose_name='שם רופא')),
                ('client_id', models.CharField(max_length=50, verbose_name='תז מטופל')),
                ('client_name', models.CharField(max_length=50, verbose_name='שם מטופל')),
                ('date_app', models.DateField(verbose_name='תאריך טיפול')),
            ],
        ),
        migrations.AlterField(
            model_name='survey',
            name='cleaning',
            field=models.CharField(max_length=20, verbose_name='רמת נקיון בבית החולים'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='facilities',
            field=models.CharField(max_length=20, verbose_name='תחזוקת המקום (שירותים, גינון וכולי)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='food',
            field=models.CharField(max_length=20, verbose_name='רמת האוכל המוגש בבית החולים'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='security',
            field=models.CharField(max_length=20, verbose_name='רמת האבטחה בבית החולים'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='treatment',
            field=models.CharField(max_length=20, verbose_name='הטיפול הרפואי שקיבלת'),
        ),
    ]
