# Generated by Django 4.1.4 on 2023-01-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claritymedapp', '0002_doc_app_alter_survey_cleaning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navs', models.TextField()),
            ],
        ),
    ]
