# Generated by Django 4.1.4 on 2023-01-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claritymedapp', '0003_navclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='navclass',
            name='name_class',
            field=models.CharField(max_length=50, null=True, verbose_name='class name'),
        ),
    ]
