# Generated by Django 4.1.4 on 2023-01-05 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('claritymedapp', '0005_clients1'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients1',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doc_app',
            name='doc_id',
            field=models.CharField(max_length=50, verbose_name='מספר רופא'),
        ),
    ]
