# Generated by Django 4.1.4 on 2023-01-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claritymedapp', '0006_clients1_user_alter_doc_app_doc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='recep_eq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eq', models.CharField(max_length=50, null=True, verbose_name='שם המוצר')),
                ('price', models.CharField(max_length=50, null=True, verbose_name='מחיר')),
                ('des', models.TextField()),
            ],
        ),
    ]
