# Generated by Django 4.1.4 on 2023-01-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claritymedapp', '0007_recep_eq'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_recep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qunt1', models.IntegerField(verbose_name=' כמות להזמנה ')),
                ('qunt2', models.IntegerField(verbose_name=' כמות להזמנה ')),
                ('qunt3', models.IntegerField(verbose_name=' כמות להזמנה ')),
                ('qunt4', models.IntegerField(verbose_name=' כמות להזמנה ')),
                ('qunt5', models.IntegerField(verbose_name=' כמות להזמנה ')),
                ('qunt6', models.IntegerField(verbose_name=' כמות להזמנה ')),
                ('qunt7', models.IntegerField(verbose_name=' כמות להזמנה ')),
            ],
        ),
    ]
