# Generated by Django 4.1.4 on 2023-01-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claritymedapp', '0008_order_recep'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_recep',
            name='qunt8',
            field=models.IntegerField(null=True, verbose_name=' כמות נייר מדפסת להזמנה '),
        ),
        migrations.AlterField(
            model_name='order_recep',
            name='qunt1',
            field=models.IntegerField(null=True, verbose_name=' כמות חבילת עטים להזמנה '),
        ),
        migrations.AlterField(
            model_name='order_recep',
            name='qunt2',
            field=models.IntegerField(null=True, verbose_name=' כמות קלסר משרדי להזמנה '),
        ),
        migrations.AlterField(
            model_name='order_recep',
            name='qunt3',
            field=models.IntegerField(null=True, verbose_name=' כמות סיכות לשדכן להזמנה '),
        ),
        migrations.AlterField(
            model_name='order_recep',
            name='qunt4',
            field=models.IntegerField(null=True, verbose_name=' כמות תיקי הגשה להזמנה '),
        ),
        migrations.AlterField(
            model_name='order_recep',
            name='qunt5',
            field=models.IntegerField(null=True, verbose_name=' כמות שדכן סיכות להזמנה '),
        ),
        migrations.AlterField(
            model_name='order_recep',
            name='qunt6',
            field=models.IntegerField(null=True, verbose_name=' כמות מטליות חיטוי להזמנה '),
        ),
        migrations.AlterField(
            model_name='order_recep',
            name='qunt7',
            field=models.IntegerField(null=True, verbose_name=' כמות דיו מדפסת להזמנה '),
        ),
    ]
