# Generated by Django 4.1.4 on 2023-01-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claritymedapp', '0009_order_recep_qunt8_alter_order_recep_qunt1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc_eq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eq', models.CharField(max_length=50, null=True, verbose_name='שם המוצר')),
                ('price', models.CharField(max_length=50, null=True, verbose_name='מחיר')),
                ('des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='order_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qunt1', models.IntegerField(null=True, verbose_name=' כמות כפפות להזמנה ')),
                ('qunt2', models.IntegerField(null=True, verbose_name=' כמות מסכות להזמנה ')),
                ('qunt3', models.IntegerField(null=True, verbose_name=' כמות חלוק רפואי להזמנה ')),
                ('qunt4', models.IntegerField(null=True, verbose_name=' כמות מזרקים להזמנה ')),
                ('qunt5', models.IntegerField(null=True, verbose_name=' כמות תחבושות להזמנה ')),
                ('qunt6', models.IntegerField(null=True, verbose_name=' כמות חומר חיטוי להזמנה ')),
                ('qunt7', models.IntegerField(null=True, verbose_name=' כמות פד גזה להזמנה ')),
                ('qunt8', models.IntegerField(null=True, verbose_name=' כמות מבחנות להזמנה ')),
            ],
        ),
    ]
